version: 0.2

env:
  variables:
    #TF_VERSION: from code pipeline

phases:
  install:
    commands:
      - wget https://releases.hashicorp.com/terraform/$(TF_VERSION)/terraform_$(TF_VERSION)_linux_amd64.zip
      - unzip terraform_$(TF_VERSION)_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - chmod +x /usr/local/bin/terraform
      - terraform version
  pre_build:
    commands:
      - cd terraform
      - terraform init
  build:
    commands:
      - terraform apply -auto-approve -no-colour -out=tfplan tfplan
  post_build:
    commands:
      - echo "Terraform apply completed on $(date)."

