version: 0.2

phases:
  install:
    commands:
      - echo ${TF_VERSION}
      - sudo su
      - curl -LO https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
      - unzip -o terraform_${TF_VERSION}_linux_amd64.zip -d /tmp/terraform
      - mv /tmp/terraform/terraform /usr/local/bin/terraform
      - chmod +x /usr/local/bin/terraform
      - terraform version
  pre_build:
    commands:
      - pwd
      - ls -la
      - cd terraform/pipelines-to-deploy
      - terraform init -backend-config="key=${BACKEND_CONFIG_KEY}"
  build:
    commands:
      - terraform apply -auto-approve -no-color

  post_build:
    commands:
      - echo "Terraform apply completed on $(date)."
